import { Food } from "@/types";

export const DEFAULT_FOODS: Omit<Food, "id">[] = [
  { name: "白米", calorie: 168, protein: 2.5, fat: 0.3, carb: 37.1, unit: "g", servingSize: 150, category: "grain" },
  { name: "玄米", calorie: 165, protein: 2.8, fat: 1.0, carb: 34.2, unit: "g", servingSize: 150, category: "grain" },
  { name: "食パン(6枚切)", calorie: 158, protein: 5.6, fat: 2.6, carb: 28.0, unit: "枚", servingSize: 1, category: "grain" },
  { name: "オートミール", calorie: 380, protein: 13.7, fat: 5.7, carb: 69.1, unit: "g", servingSize: 40, category: "grain" },
  { name: "鶏むね肉(皮なし)", calorie: 108, protein: 22.3, fat: 1.5, carb: 0, unit: "g", servingSize: 150, category: "meat" },
  { name: "ささみ", calorie: 98, protein: 23.0, fat: 0.8, carb: 0, unit: "g", servingSize: 100, category: "meat" },
  { name: "鶏もも肉(皮なし)", calorie: 127, protein: 19.0, fat: 5.0, carb: 0, unit: "g", servingSize: 150, category: "meat" },
  { name: "牛赤身肉", calorie: 193, protein: 21.3, fat: 11.7, carb: 0.6, unit: "g", servingSize: 100, category: "meat" },
  { name: "豚ロース(脂身なし)", calorie: 150, protein: 22.7, fat: 6.0, carb: 0.1, unit: "g", servingSize: 100, category: "meat" },
  { name: "サーモン", calorie: 208, protein: 20.1, fat: 13.6, carb: 0.1, unit: "g", servingSize: 80, category: "fish" },
  { name: "マグロ赤身", calorie: 115, protein: 26.4, fat: 1.4, carb: 0.1, unit: "g", servingSize: 80, category: "fish" },
  { name: "卵", calorie: 76, protein: 6.4, fat: 5.1, carb: 0.3, unit: "個", servingSize: 1, category: "dairy" },
  { name: "牛乳", calorie: 61, protein: 3.3, fat: 3.8, carb: 4.8, unit: "ml", servingSize: 200, category: "dairy" },
  { name: "ギリシャヨーグルト(無糖)", calorie: 60, protein: 10.0, fat: 0.4, carb: 4.0, unit: "g", servingSize: 100, category: "dairy" },
  { name: "カッテージチーズ", calorie: 99, protein: 13.3, fat: 4.5, carb: 1.9, unit: "g", servingSize: 100, category: "dairy" },
  { name: "納豆", calorie: 90, protein: 7.4, fat: 4.5, carb: 5.4, unit: "パック", servingSize: 1, category: "other" },
  { name: "豆腐(絹)", calorie: 56, protein: 4.9, fat: 3.0, carb: 2.0, unit: "g", servingSize: 150, category: "other" },
  { name: "サラダチキン", calorie: 124, protein: 25.0, fat: 1.3, carb: 1.8, unit: "個", servingSize: 1, category: "meat" },
  { name: "ゆで卵", calorie: 77, protein: 6.5, fat: 5.2, carb: 0.3, unit: "個", servingSize: 1, category: "dairy" },
  { name: "高タンパクパン", calorie: 194, protein: 13.5, fat: 5.8, carb: 21.8, unit: "個", servingSize: 1, category: "grain" },
  { name: "プロテインバー", calorie: 190, protein: 20.0, fat: 7.0, carb: 18.0, unit: "本", servingSize: 1, category: "supplement" },
  { name: "ブロッコリー", calorie: 37, protein: 4.3, fat: 0.5, carb: 4.3, unit: "g", servingSize: 100, category: "vegetable" },
  { name: "バナナ", calorie: 93, protein: 1.1, fat: 0.2, carb: 22.5, unit: "本", servingSize: 1, category: "fruit" },
  { name: "アーモンド", calorie: 587, protein: 21.3, fat: 54.1, carb: 11.0, unit: "g", servingSize: 25, category: "snack" },
  { name: "おにぎり", calorie: 175, protein: 5.0, fat: 2.0, carb: 34.0, unit: "個", servingSize: 1, category: "grain" },
  { name: "ホエイプロテイン", calorie: 117, protein: 23.0, fat: 2.0, carb: 3.0, unit: "g", servingSize: 30, category: "supplement" },
  { name: "カゼインプロテイン", calorie: 113, protein: 22.0, fat: 1.5, carb: 4.0, unit: "g", servingSize: 30, category: "supplement" },
  { name: "ソイプロテイン", calorie: 111, protein: 21.0, fat: 2.0, carb: 5.0, unit: "g", servingSize: 30, category: "supplement" },
];
